### ISSUE TITLE
blpConnect Failed to start session. Connection Failed

### ISSUE THREAD

**Issue by monisr** [Rblp/Rblpapi#193]
blpConnect fails to start session.
I have tried using the following:

blpConnect()
blpConnect(host = getOption("blpHost", "localhost"),port = getOption("blpPort", 8194L), default = TRUE)
blpConnect(host = "127.0.0.1", port = 8194L, default = TRUE)

this is what i get

> blpConnect()

05AUG2016_15:52:03.720 1420:123145311383552 ERROR blpapi_platformtransporttcp.cpp:671 blpapi.session.transporttcp.{5}.<localhost:8194> Connection failed 

05AUG2016_15:52:03.720 1420:123145311383552 WARN blpapi_platformcontroller.cpp:371 blpapi.session.platformcontroller.{5} Platform: 0 failed 1 consecutive connect attempts, stopped trying to reconnect. 
Error: Failed to start session.

While installing rblpapi package i had some warnings: (these were in subscribe.cpp so i doubt they make a difference)
subscribe.cpp:109:22: warning: expression result unused [-Wunused-value]
    if(e.isNull()) { R_NilValue; }
                     ^~~~~~~~~~
subscribe.cpp:110:10: warning: unused variable 'ans' [-Wunused-variable]
    SEXP ans;
         ^
2 warnings generated.

System Info:
OSX 10.11.5 EL CAPITAN

Rstudio Version 0.99.484

> R.version
               _                           
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          3.1                         
year           2016                        
month          06                          
day            21                          
svn rev        70800                       
language       R                           
version.string R version 3.3.1 (2016-06-21)
nickname       Bug in Your Hair            

Let me kno if any other information is required

**Comment by wmorgan85** [comment]
You need to have a bbcomm instance running for the session to start. This message suggests that it's not running.

**Comment by monisr** [comment]
thanks. Ill install bloomberg anywhere with the excel add-in.

just saw issue 152. Sorry about the repeat.
https://github.com/Rblp/Rblpapi/issues/152

**Comment by henrywoo** [comment]
@monisr How did you make it work? I installed Bloomberg anywhere with excel plugin but still got the same error.

```
> blpConnect()

17AUG2016_19:48:46.272 18236:8368 ERROR blpapi_platformtransporttcp.cpp:671 blpapi.session.transporttcp.{1}.<localhost:8194> Connection failed 

17AUG2016_19:48:46.272 18236:8368 WARN blpapi_platformcontroller.cpp:371 blpapi.session.platformcontroller.{1} Platform: 0 failed 1 consecutive connect attempts, stopped trying to reconnect. 
Error: Failed to start session.
```

**Comment by eddelbuettel** [comment]
The key here is @wmorgan85 's comment: `bbcomm.exe` must be running, and `bbcomm.exe` is part of the standard Bloomberg Desktop installation.

**Comment by tchevri** [comment]
Hi Dirk - thank you for highlighting this - it helped me getting your package Rblpapi working just fine, as expected, BUT on a windows machine.  However, i was hoping to get it to work under Ubuntu too - given that this is a windows executable file, is there a way to get this bbcomm or equivalent running under linux?  you mention in your documentation that it works across all platforms... but googling for several hours and have not really seen anything useful... 
I also looked at http://dirk.eddelbuettel.com/papers/rfinance2016_may2016_rblpapi.pdf  and your slides talks about the implications of bbcomm.exe without saying much..
fyi, after installing citrix for linux, i was able to run bbg anywhere in ubuntu with the excel add in.  The excel add in works just fine - it opens up an excel book with all the bbg functions loaded and i can download data (so not sure what that data licensing you mention is about, since i CAN get the data in excel in ubuntu!!).  However, when in R I use that same blpconnect() function that works just fine on the windows machine with bbcomm running, it fails with:
ERROR blpapi_platformtransporttcp.cpp:671 blpapi.session.transporttcp.{3}.<localhost:8194> Connection failed
I hope I did not miss anything obvious - if I did, please don't get upset with me.
FYI, I have not tried this yet:  http://stackoverflow.com/questions/35458939/error-blpapi-platformtransporttcp-cpp671-connection-issue-in-r
thanks a lot in advance for any help you may provide - you have no idea just how many times your answers buried all over the internet have helped me out when i faced a problem - here's my chance to say thank you for that in any case.
many thanks
thomas
