### ISSUE TITLE
getPortfolio returns Unknown/Invalid Security

### ISSUE THREAD

**Issue by OM77** [Rblp/Rblpapi#238]
> getPortfolio(security="OPTYX026", field="Value GBP", verbose=TRUE, identity=NULL, con=bl.con)
PortfolioDataResponse = {
    securityData[] = {
        securityData = {
            security = "OPTYX026"
            eidData[] = {
            }
            securityError = {
                source = "204::bbdbl2"
                code = 15
                category = "BAD_SEC"
                message = "Unknown/Invalid Security  [nid:204] "
                subcategory = "INVALID_SECURITY"
            }
            fieldExceptions[] = {
            }
            sequenceNumber = 0
            fieldData = {
            }
        }
    }
}
NULL

**Comment by joel23888** [comment]
This does not seem like an `Rblpapi` issue. Looking at your security, it seems you need to 'tickerize' your portfolio and then use its BBG ticker here. The BBG Helpdesk could walk you through this.

**Comment by joel23888** [comment]
@OM77 actually a correction to what I said above. Follow the steps below. I found this out during my own investigation and decided to detail it here because I needed to refer to an older version of the BBG API Developer's Guide to get the parameters right.

1. Create a portfolio through the PRTU function in the BBG terminal, or use an existing one. BBG Helpdesk can walk you through this. It is *not* necessary to tickerize the portfolio to use with `getPortfolio`. However, tickerization is required to use it with other `Rblpapi` functions such as `bdp` or `bdh`.
2. The `security` parameter in `getPortfolio` should be the portfolio's ID from PRTU with ' Client' appended. The portfolio ID can be found by loading the portfolio in PRTU. For example, if the portfolio ID is 'U12345678-9' then the `security` parameter would be 'U12345678-9 Client'.
3. The `field` parameter should be one of: 'PORTFOLIO_MEMBER', 'PORTFOLIO_MPOSITION', 'PORTFOLIO_MWEIGHT', or 'PORTFOLIO_DATA'.
4. There are no options documented.
5. There is one override available in order to set the reference date. For example you could include something like `overrides=c(REFERENCE_DATE='20170801')`.

Ref: p178 at https://data.bloomberglp.com/labs/sites/2/2014/07/blpapi-developers-guide-2.54.pdf

**Comment by OM77** [comment]
Thanks joel23888.
The fields that can be used are: PORTFOLIO_MEMBER, PORTFOLIO_MPOSITION,, PORTFOLIO_MWEIGHT & PORTFOLIO_DATA. I can't get the delta or premium of an option in my portfolio?

**Comment by joel23888** [comment]
This is what was documented in the BBG C++ API Developer's Guide. `Rblpapi` is dependent on that. Can you ask BBG to see if they have a (possibly undocumented) field which matches your needs? If there is a field name available in their API, you could pass it as the `field` parameter. I doubt there will be, but it is worth your asking them.

**Comment by joel23888** [comment]
Also, could you use `bdp` with the option ticker to get the delta/premium after getting the option ticker using `getPortfolio`? that would seem a reasonable approach.
