### ISSUE TITLE
Shiny App Integration

### ISSUE THREAD

**Issue by kevinho1996** [Rblp/Rblpapi#297]
Based on Bloomberg licensing agreement and terms of service, can we actually make a shiny app connecting to Bloomberg?

**Comment by armstrtw** [comment]
I suggest you talk to your Bloomberg rep or general counsel.

**Comment by n-e-w** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  IANAL etc etc. I am especially not *your* lawyer. Read the terms of the agreement carefully. Perhaps you might find scope that if your shiny app resides on the same machine as your Bloomberg desktop license and you don't allow the Bloomberg data to leave that machine then a shiny app would, indeed, probably fall within the ambit off your license. Technically, yes, it is possible.                                                                                                                                                                                                                                                                                                                         From: notifications@github.comSent: 21 November 2019 23:51To: Rblpapi@noreply.github.comReply to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: [Rblp/Rblpapi] Shiny App Integration (#297)  Based on Bloomberg licensing agreement and terms of service, can we actually make a shiny app connecting to Bloomberg?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

This email is confidential. If you have received it in error, please destroy this email and any/all attached documents immediately. Please also notify the sender. This message is not a solicitation and, without express information to the contrary, does not take into account the investment objectives (or otherwise) of each client, or prospective client. The information herein is for the private information of the recipient and is not to be construed as an offer to sell or solicitation to buy any interest in particular funds or securities which are referred to herein.Any simulated historic/statistical analyses that are provided in connection with explanations of the potential returns of the Product use simulated analysis and hypothetical circumstances to estimate how the Product may have performed prior to their actual existence.Neither the provision nor the content of this email creates any obligations or liability of STK. towards the users. STK does not make any representations, warranties, express or implied, as to the quality, accuracy, timeliness, continued availability or completeness of the information contained herein, including, but not limited to, the contents of any private placement memorandum or fund fact sheet. STK accepts no liability relating to direct or indirect losses, immaterial damage or consequential damage including loss of profit (even where STK has been made aware of the possibility of such damages). This limitation of liability also holds for directors and employees of STK. The information in this email has been prepared on information deemed to be reliable. STK Management Pty Ltd does not represent that this material is accurate, complete or current, and accepts no liability if it is not. STK, its subsidiaries and partners may have positions in - and buy or sell - any of the securities mentioned in this e-mail without notice.ACN: 163028171 AFSL: 446261
