### ISSUE TITLE
Change parameter name from excludeTerm to FieldType

### ISSUE THREAD

**Issue by Karnner2** [Rblp/Rblpapi#306]
In the fieldSearch method, your parameter excludeTerm is actually the fieldType that Bloomberg's FLDS provides. If you default to Static we do not get all of the terms. Default to 'All' and change the name so that it is clearer what this parameter does.

**Comment by johnlaing** [comment]
Yeah, this seems wrong. I think we were trying to follow the example from the dev guide it doesn't make sense as a general case. Because the `fieldType` setting is inside an `exclude` element it seems to be doing the opposite of what we expected.

We should probably deprecate this argument altogether. @eddelbuettel any thoughts/issues?

**Comment by eddelbuettel** [comment]
I am a bit removed from the day to day so it is a little tricky for me to comment in a meaningful way.

**Comment by johnlaing** [comment]
I ask only because you wrote the function initially, but that was many years ago. I'll submit the change, pretty sure it's the right thing to do.

**Comment by Karnner2** [comment]
Thanks, gents!
