### ISSUE TITLE
Does this work with Bloomberg anywhere?

### ISSUE THREAD

**Issue by CaleCornelius** [Rblp/Rblpapi#319]
Hi team,
I'm attempting to use blpConnect in conjuction with my Bloomberg anywhere subscription. 
I have attempted [this fix](https://stackoverflow.com/questions/35458939/error-blpapi-platformtransporttcp-cpp671-connection-issue-in-r). I have the excel add-in installed per stackoverflow guidance. [In addition](https://stackoverflow.com/questions/17304714/bloomberg-cant-start-session), I am running BBcomm.exe through the command line on my windows machine, but I am still receiving the following error:

```
15JAN2021_16:01:46.997 15340:22144 ERROR blpapi_platformtransporttcp.cpp:671 blpapi.session.transporttcp.{2}.<localhost:8194> Connection failed 
Error in blpConnect_Impl(host, port, appName) : Failed to start session.

15JAN2021_16:01:46.997 15340:22144 WARN blpapi_platformcontroller.cpp:371 blpapi.session.platformcontroller.{2} Platform: 0 failed 1 consecutive connect attempts, stopped trying to reconnect. 
```
Apologies in advance if this is too similar to error #152 but I'm hoping that my just using vanilla windows means I'll be able to run the package succesfully.

**Comment by wmorgan85** [comment]
Hi there. It sounds like the same issue as #152. Are you running Bloomberg Anywhere from the browser, or have you installed the terminal and Excel add-ins? That's a pre-requisite.

**Comment by CaleCornelius** [comment]
Hi Morgan, 

Thanks for the prompt response. Having spoken to my Bloomberg rep, I'm currently accessing the terminal through the disaster recovery option, although I do have the excel add in installed and said excel functionality is working fine. Does this mean I should use excel instead of the R-API?
Thanks,
Cale

**Comment by wmorgan85** [comment]
Hey Cale

Ok so if your Excel add-in is working then everything should be fine. You shouldn't need to run BBCOMM manually, as it will run in the background when you start your Bloomberg up.

One thing that I can think of is that perhaps your BBCOMM isn't running on port 8194. There are a few anti-virus programs, Sophos being one, that use that port by default and block Bloomberg functionality. 

The other thing that is worth trying is to use the API Diagnostic Tool that should be located in the Bloomberg part of your start menu. That will highlight whether the standard BBG implementation of the programmatic API is having issues connecting.

As for whether you should use Excel instead of the R-API it all depends what you want to do and how much patience you have :)

Morgan

**Comment by CaleCornelius** [comment]
Hi Morgan,

Ok perfect thanks, I ultimately figured out how to get the data I needed using the Excel API, but appreciate you taking the time to explain.
Thanks again,
Cale
