### ISSUE TITLE
VWAP_VOLUME request does not return the same results as in Excel

### ISSUE THREAD

**Issue by travis-leith** [Rblp/Rblpapi#358]
For the following variations, I get no result

```R
> bdp("AMS LN Equity","VWAP_VOLUME", overrides = c(VWAP_START_DT = "20210101", VWAP_END_DT = "20210101"))
              VWAP_VOLUME
AMS LN Equity          NA
> bdp("AMS LN Equity","VWAP_VOLUME", overrides = c(VWAP_START_DT = "2021-01-01", VWAP_END_DT = "2021-01-01"))
              VWAP_VOLUME
AMS LN Equity          NA
> bdp("AMS LN Equity","VWAP_VOLUME", overrides = c(VWAP_START_DT = as.Date("2021-01-01"), VWAP_END_DT = as.Date("2021-01-01")))
              VWAP_VOLUME
AMS LN Equity          NA
```

But in Excel, I get a result

![image](https://user-images.githubusercontent.com/29927084/149179920-46c7095b-7519-40a7-8bee-284a8ef05f20.png)

I can do what I need to get done in Excel, but I thought I'd report the discrepancy here.

**Comment by armstrtw** [comment]
I don't have access to a terminal at the moment, but just try changing your date format to %Y%m%d, i.e. without the '-' separator.  From memory, I think this has come up before with overrides, so perhaps search previous opened issues as well.

**Comment by armstrtw** [comment]
Looks like you are passing in new year's day to bdp, but the 12th in excel.

**Comment by mtkerbeR** [comment]
Correcting for the date, the code works as expected:

```
library(Rblpapi)
blpConnect()

bdp("AMS LN Equity","VWAP_VOLUME", overrides = c(VWAP_START_DT = "20211201", VWAP_END_DT = "20211201"))
#>               VWAP_VOLUME
#> AMS LN Equity      120502
```

**Comment by eddelbuettel** [comment]
Some of this code is old. I have since written code where I use `anytime::anydate` to _reliably_ go from a text of date in just about any format to a `Date` object.  (And that use case was one of the motivations for `anytime` as I got tired of having to spec dates when most people _automagically_ write something close enough to ISO 8601 standards....

We could do the same here at the cost of an added dependency (or use a helper function shadowing that idea if we like the approach but hate the dependency).

**Comment by travis-leith** [comment]
sorry about this, sill mistake on my part.

**Comment by eddelbuettel** [comment]
No worries, stuff happens.  We all have overlooked a bad option setting here or there before.
