### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by vathymut** [Rblp/Rblpapi#40]
I'm not sure if you accept feature requests but this is one :)  It'd be great to have Windows support. 

I don't have admin privileges on the Bloomberg terminal/machine -- I doubt many Bloomberg users will. It makes it tricky for seamless `Rtools` and `Rcpp` integration.
I tried:

    require( devtools )
    devtools::install_github( "Rblp/Rblpapi" )

It seems I'm unable to edit/append to the system path (`Error creating registry key` when installing `Rtools`).

Any plans to support Windows?

**Comment by avanchev** [comment]
I have faced with the same issue even though I have admin rights.  It would not compile on Windows.  I am currently using Rbbg 0.5.3 with R 3.1.3 and it is working without errors.

**Comment by armstrtw** [comment]
I have no ability to test on windows as I do not have a windows development machine.

I think it may be more complicated than just getting it to compile as the windows DLL's are not built w/ mingw.

**Comment by eddelbuettel** [comment]
Seconding what @armstrw just said:  because of the way C++ libraries are organized, you cannot generally link code from one compiler (ie visual c++ for the bloomberg library) with code from another (ie g++ from the R toolchain).   

If you are truly motivated you can do so with plain C, meaning that every function called from R (and the Rblpapi package) into the Bloomberg API dll would have to be mediated through a C layer.   We are unlikely to do this work, but could possibly try to someone attempting to do it in order to get the Windows platform going.

Otherwise your only hope is to convince Bloomberg to compile their library with the MinGW g++ from Rtools.  I tried, but no success.

**Comment by ungil** [comment]
Works (for me, at least) using the src/Makevars file below. Note that the path to the Bloomberg libraries is .../bin and not .../lib
There might be a more elegant way to force the use of the .dll files instead of the .lib files present at lib, which happen to interfere with the build.

========================
```
CXX_STD      = CXX11

ifeq "$(WIN)" "64"
	BBG_LIB=blpapi3_64
else
	BBG_LIB=blpapi3_32
endif

BBG_PATH   = C:/blp/API/APIv3/C++API/v3.6.2.0

PKG_CPPFLAGS = -I$(BBG_PATH)/include -I.
PKG_LIBS     = -l$(BBG_LIB) -L$(BBG_PATH)/bin
```

**Comment by eddelbuettel** [comment]
If you made that `src/Makevars.win` and maybe made the `BBG_PATH` an argument of an environment variable we could take this as a pull request.

However, I won't be able to test this for a couple of days.  Could you check back in, say, early July?

**Comment by ungil** [comment]
I'm not familiar with package building, I don't know how to pass and handle environment variables. It might be easier to include all the needed bits.

By the way, the latest release of the API raises type errors on Windows. 3.7.9.1 does work, it can be downloaded from http://static.bloomberglabs.com/api/cpp/blpapi_cpp_3.7.9.1-windows.zip

I copied the header files to _inst/include_ (but a different directory would be needed to coexists with Linux) and the dlls to _inst/libs/x64_ and _inst/libs/i386_ (is it possible to avoid prevent them from appearing in the binary packages for other platforms?). I get a self-contained package that can be built with the following _src/Makevars.win_

```
CXX_STD = CXX11

PKG_CPPFLAGS = -I../inst/include -I.

ifeq "$(WIN)" "64"
	PKG_LIBS = -blpapi3_64 -L../inst/libs/x64
else
	PKG_LIBS = -blpapi3_32 -L../inst/libs/i386
endif
```

The resulting binary (the output of "R CMD INSTALL --build --with-keep.source Rblpapi") contains the blpapi and Rblpapi dlls. I would share it, but I don't this is actually allowed by the Rblpapi license. See http://www.gnu.org/licenses/gpl-faq.en.html#GPLIncompatibleLibs

**Comment by jrowen** [comment]
@ungil I'd be happy to assist with creating/testing a Windows PR.  I have experience with package building but not as much with C++.  Would it make sense to create a fork, and then we can submit a PR once we've worked out the details?

**Comment by avanchev** [comment]
That would be awesome.  I wish I could help too.

**Comment by eddelbuettel** [comment]
Yes, a fork and a PR would be the cleanest and most common way to do this.  I can help you -- but am traveling on limited bandwith.

**Comment by jrowen** [comment]
[Here's](https://github.com/jrowen/Rblpapi/tree/windows) a first attempt at incorporating the suggested changes.  I can get the package to compile in RStudio with 3.7.9.1 (haven't tried other versions), but I'm running into the error below when trying to use the package.
```
> library(Rblpapi)
> con <- blpConnect()
> goog.ge.px <- bdp(con, securities=c("GOOG Equity"), fields=c("PX_LAST"))
 Error in eval(expr, envir, enclos) : not compatible with STRSXP 
```
Before building the package, you'll need to run `inst/scripts/getBloombergAPI.R` to download the library files.

**Comment by ungil** [comment]
@jrowen, the con parameter is not needed (the documentation is outdated). The following should work:

```
bdp("GOOG Equity","PX_LAST")
```

Thanks for applying the changes.

**Comment by avanchev** [comment]
I was able to compile as well.  
This however gave me an error:

> spx <- bdh(securities='SPX Index', fields='PX_LAST', start.date='2013:03:01')
Error: start.date must be a Date object

**Comment by jrowen** [comment]
@ungil Thanks for the pointer, that worked.

@avanchev Try something like
```
bdh('SPX Index', 'PX_LAST', as.Date('2013-03-01'))
```
I wait a bit to gather any feedback on the changes and then submit a PR.

**Comment by eddelbuettel** [comment]
Can you point out where the documentation still mentions `con` arguments in the first position?

**Comment by jrowen** [comment]
I was looking at Examples section of the [README](https://github.com/Rblp/Rblpapi/blob/master/README.md) file.  I think a few other item are out-of-date with that code as well.

**Comment by ungil** [comment]
@jrowen : I have a few comments. 

You might have noticed already that the download.file call is commented out in getBloombergAPI.R

I had problems with the Rscripts calls in configure.win because my .Rprofile prints out some things at startup. I guess some other people might have the same issues. When I defined rpath by hand I still had problems because it contained spaces (I'm not sure if I would have encountered this problem had the variable been set by the script).

I suspect the -rpath doesn't have an effect on Windows. You might be using the copy of the blpapi dll already in the path... 

Another issue it that (at least by default) if there is a configure.win the package is built for a single architecture. If there is no configure.win (and Makevars.win is included) the output will contain both i386 and x86 binaries.

For what it's worth, I have created a fork with the simpler approach I described (but I understand why a more complex solution might be desired). A problem is that the DLLs will appear in the binaries for other platforms (but maybe the configure scripts for this platforms could delete the files when building the package). The following should just work:

devtools::install_github("ungil/Rblpapi")

**Comment by eddelbuettel** [comment]
@ungil:

- please try to work on PR in a unified repo
- rpath very much is Linux only and not your concern, as I said before for Windows we have `src/Makevars.win` anyway
- change your very own `.RProfile` by printing only if  `if (interactive()) { ... }`  which I do (and recommend)
- not sure how to deal with the 32 vs 64 bit issue yet; also do not know what style Bloomberg itself installs---maybe we can just focus on 64-bit Windows?

**Comment by ungil** [comment]
@eddelbuettel : My knowledge of git doesn't go beyond the basics (I don't even use branches) and I've not used github before. I don't know how to work on "a PR in a unified repo". I know it would make collaboration easier, but I'll let a more knowledgeable person who is also interested on Windows support work out the details. At least not knowing github workflows didn't prevent me from pointing out that it is indeed possible to use Rblpapi on Windows :-)

Of course it will be nice to see windows officially supported. This is why I sent these comments to @jrowen (I was not particularly concerned by rpath until I tested his proposal). Thanks for pointing out the "if (interactive())" solution. In fact this message was added just yesterday when I installed another package, I don't know how often it might cause problems. But I'm sure other potential users of Rblpapi will encounter the same difficulty. 

I have no strong feelings about 32bits vs. 64bits. But people might have reasons to want to use 32bit R even when running 64bit Windows (for example, to be able to use other packages or to embed R on a program that depends on other 32bit-only components).

**Comment by jrowen** [comment]
@ungil Sorry about the `download.file` comment, I've removed it.  

To make testing easier, I added the necessary windows libraries.  Let me know if there is a better folder structure to follow.  You should now be able to install only with
```r
devtools::install_github("jrowen/Rblpapi", ref = "windows")
```
I set this up to re-use the `Makevars.in` file, but if the rpath doesn't apply and causing problems in Windows, I could create a `Makevars.win.in` version instead (that doesn't include `-Wl,-rpath,$(BBG_RPATH)` for example).  For what it's worth, I also ran into this problem previously and updated my `.RProfile` to use `interactive`.

Keep the suggestions coming, and feel free to submit a PR directly to [this](https://github.com/jrowen/Rblpapi/tree/windows) branch if that's easier.

**Comment by ungil** [comment]
@jrowen : I managed to suppress the startup message for the test (by a brute force approach, commenting out a "source" done at the Profile.site level that ends loading some libraries). But I still have the other problem I mentioned, the configure.win script doesn't like the space in "Program Files".

Otherwise it works... as long as the system already contains blpapi_64.dll in C:/blp/API (or elsewhere in the path). The included file is used to compile Rblpapi.dll, but I don't think there is a way to tell the package to use the dll available at inst/win at runtime.

There might be no point in including the dll in the installed package if it's not in inst/libs/x64 (which might go against the recommended practice). Strictly speaking the header files are not needed in the binary distribution either, but at least can be helpful for reference. It's of course useful to include the dll in the source package, so a binary can be produced without requiring configuration and on a bloomberg-less host.

I've also discovered that my fork didn't work properly either. The libraries have to be called blpapi_32 and blpapi_64. I renamed them to specify the version and they were used for the compilation but not at runtime (a dll knows its true name, and Rblpapi.dll will reference it). With the right name, they will be loaded if they are in the same directory as Rblpapi.dll (before other versions present in the path, if I'm not mistaken).

Thanks again for your work. You might want to wait for feedback from other windows users and discuss with the package mantainers about the best folder structure and policy for downloading/including/referencing the required headers and libraries.

**Comment by jrowen** [comment]
As I mentioned earlier, my C++ knowledge is limited, so a few questions:
* Would it make sense to add a check to verify that the necessary dll is in the path or do we assume that the user understands this?  I'm assuming the terminal app also needs to be installed for the this to work.
* The `Makevars.win` file created from `configure.win` specifies
```
BLP_PATH    = /inst/win/
```
so is it still necessary to place the dlls in inst/libs/x64?

The full `Makevars.win` file is
```
## -*- mode: makefile; -*-

## use C++11
CXX_STD      = CXX11

## filled in by configure
BBG_LIB     = blpapi3_64
BBG_RPATH   = C:/Users/jrowen/Documents/R/win-library/3.2/Rblpapi/win
BLP_PATH    = /inst/win/
HEADER_PATH = /inst/win/include/

## set include and linker options
## Bbg API files are assummed to be in the standard search path
PKG_CPPFLAGS = -I..$(HEADER_PATH) -I.
PKG_LIBS     = -l$(BBG_LIB) -L..$(BLP_PATH) -Wl,-rpath,$(BBG_RPATH)
```

**Comment by ungil** [comment]
Probably the end user can be assumed to have blpapi3_64.dll (I'll leave aside the 32bit case) somewhere in the PATH (at C:/blp/API/ or at some other location). At least this is the default for Desktop users, I'm not sure about other kinds of Bloomberg installations. If we want to include our own copy, it has to be put into inst/libs/x64 so in the end it appears in R_HOME/library/Rblpapi/libs/x64 together with Rblpapi.dll (otherwise it won't be used unless the user modifies the PATH or the dll is moved where it can be found).

A different situation is building the package. One might want to build the binary package in a bloomberg-less machine (for example if one cannot access a machine with both Rtools and Bloomberg installed). 
The linker needs to be told there the library is, it's not enough that it's somewhere on the PATH. This corresponds to the  "-L..$(BLP_PATH)"  fragment (the "-Wl,-rpath,$(BBG_RPATH)" part is irrelevant on Windows).

Here there are a number of solutions. For example,
1) we set "C:/blp/API" as the default location of the DLL, and rely on the the user to change the Makevars.in if needed
2) we include the dll with the source code and reference the local copy, which doesn't have to be in any particular directory (if the dll is also present already in the PATH, see below)

Unfortunately to finish the compilation of the package it has to be loaded. As discussed in the first paragraph, if the user has bloomberg the dll is probably on the path and everything is ok (we can use either solution for building, and the system dll will always be used for testing).

When Bloomberg is not available on the host, the test will fail unless the blpapi dll was in inst/libs/x64 (or the user has installed the library by himself somewhere in the PATH).

I'm afraid I have no perfect solution to offer.

**Comment by jrowen** [comment]
Thanks for the more detailed explanation.  I updated the dll path to inst/libs and removed the rpath logic from Makevars.

**Comment by eddelbuettel** [comment]
I would encourage you to take inspiration from the Linux build which is self-sufficient.   

This is harder on Windows; I once had to it at work with a vendor library.  Worst case we may have to augment $PATH just before the package gets to the loading part as the dll needs to be present--and the idea is to ship it in the package.   I think I found a wedge years ago to act in the .onLoad() / .onAttach() code before R takes over.  Things may have changed  in the meantime--the key would be to make the (package-internal) path know before R gets to the implicit loading of the dll via NAMESPACE.  Worst case we could try not to load via NAMESPACE but explicitly via `dyn.load()` after setting `PATH`.   To be continued...  

Thanks to you both for kicking the can further down the road.  We will get to Windows support with your help.

**Comment by jrowen** [comment]
I made at [attempt](https://github.com/jrowen/Rblpapi/blob/windows/R/init.R) at updating the PATH when the package loads, and with this change, it does appear that the package DLL is used.

If the API folder (c:\blp\API in my case) is not in the path, I see an error message with `blpConnect`
```
ERROR blpapi_dapisupadapter.cpp:149 DapiSupAdapter Failed to load the library: 'blpdapisup_64.dll' ...
```
but this doesn't appear to impact package functionality.  This c:\blp\API\blpdapisup_64.dll isn't part of the blpapi_cpp library, so this error could be specific to my setup.

**Comment by eddelbuettel** [comment]
Looks good (apart from style issues, I prefer `<-` assignment over `=` etc).

Won't be able to test for some time though.  Do you know about http://win-builder.r-project.org?  You'd need to put _your email_ into the Maintainer: field in `DESCRIPTION` in order to get the email though.

**Comment by eddelbuettel** [comment]
(Also the error message you saw _could_ be related to us mixing 3.8 headers and a 3.7 dll.  Just a guess...)

**Comment by jrowen** [comment]
I was not aware of win-builder, so I [ran the latest version](http://win-builder.r-project.org/imC4jS53NQ23/) of the windows branch through and am seeing a check error
```
** checking whether the package can be loaded ... ERROR
Loading this package had a fatal error status code 1
Loading log:
Error in library.dynam(lib, package, package.lib) : 
  DLL 'Rblpapi' not found: maybe not installed for this architecture?
Error: package or namespace load failed for 'Rblpapi'
```
The package appears to load fine, and I can't reproduce the check error locally.

**Comment by eddelbuettel** [comment]
I think that is the path issue in another spot.  The package compiles (per `00install.out`) but then fails the check step (per `00check.out`) when the package library file cannot be loaded for, presumably, lack of corresponding Bloomberg DLLs.

**Comment by armstrtw** [comment]
Doesn't that imply that rpath is not working on windows?

I'm sure that Uwe would install the dlls on winbuilder, but it would be great if the package could be self contained (i.e. working rpath grabbing the dlls from inst)

**Comment by eddelbuettel** [comment]
rpath is a Liniux thing, AFAIK it never worked on Windows. You need PATH.  

One can cheat and copy the Bloomberg DLL files eg into the directory into which R copies the package DLL it builds.  It's all a little hackish as its Windows...

**Comment by jrowen** [comment]
I think this check error may be because only a single arch (x64) is being built when configure.win is present.  Removing the --no-multiarch flag yields the warning
```
Warning: this package has a non-empty 'configure.win' file,
so building only the main architecture
```
but if I disable configure.win and use the Makevars.win 
```
CXX_STD = CXX11

PKG_CPPFLAGS = -I../inst/win/include -I.

ifeq "$(WIN)" "64"
    PKG_LIBS = -lblpapi3_64 -L../inst/libs/x64
else
    PKG_LIBS = -lblpapi3_32 -L../inst/libs/i386
endif
```
the [error goes away](http://win-builder.r-project.org/ZIcg7gcp0Os3/).

**Comment by eddelbuettel** [comment]
Awesome news

**Comment by jrowen** [comment]
PR #42 was merged this morning, so when you have some time please take a minute to test and let me know if you run into any issues.  I've been using it for a couple days now without any problems (wow, is it fast).  Thanks to everyone for the feedback and suggestions.

**Comment by vathymut** [comment]
@jrowen @eddelbuettel @armstrtw Gentlemen, thank you very much. I have been using 'Rblpapi' for a week now and it works without any hiccup. This is tremendous productivity boost -- no need to fiddle with the Excel plug-in.

**Comment by eddelbuettel** [comment]
:+1:

I'll return from conference travel next week and will wrap up another version.

**Comment by avanchev** [comment]
Do you know how to set the options character vector in the bdh call?  I get the following error:
Error: Request options must be named.

options	
An optional named character vector with option values. Each field must have both a name (designating the option being set) as well as a value.

name = c("Per", "Fill", "DaysC")
value = c("M", "P", "C")
options = cbind(name, value)

Thanks.

**Comment by eddelbuettel** [comment]
[This may help](https://github.com/Rblp/Rblpapi/blob/master/R/bdh.R#L40-L44).

Generally, it is better to start a new issue ticket than to hijack on old one.

**Comment by avanchev** [comment]
Thanks.  Will do next time.
